name: Copilot Billing Export

on:
  workflow_dispatch: # Manual trigger
  # schedule:
  #   - cron: '0 2 * * *' # Runs daily at 2am UTC (optional, edit/remove as needed)

jobs:
  export-copilot-billing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run Copilot Billing Script
        env:
          ENTERPRISE_SLUG: ${{ secrets.ENTERPRISE_SLUG }}
          AUTH_TOKEN: ${{ secrets.REPORTS_PAT }}
        run: |
          python copilot_billing.py

      - name: Upload billing CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: copilot-billing-csv
          path: copilot_billing_seats.csv
